import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Search, Shapes, X } from "lucide-react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useSite } from "@/components/site-shell";
import { categories, copy, products } from "@/lib/site-content";

const productSearch = z.object({ category: z.string().catch("all"), q: z.string().catch("") });
export const Route = createFileRoute("/products")({
  validateSearch: productSearch,
  head: () => ({ meta: [{ title: "Products | Sanoori Trading" }, { name: "description", content: "Browse Sanoori Trading sanitary ware, tiles, and building materials." }, { property: "og:title", content: "Products | Sanoori Trading" }, { property: "og:description", content: "Explore the Sanoori Trading digital product showroom." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "/products" }], links: [{ rel: "canonical", href: "/products" }] }),
  component: ProductsPage,
});

function ProductsPage() {
  const { language } = useSite(); const t = copy[language]; const bn = language === "bn"; const search = Route.useSearch(); const navigate = useNavigate({ from: "/products" });
  const filtered = products.filter((product) => (search.category === "all" || product.category === search.category) && product.name[language].toLowerCase().includes(search.q.toLowerCase()));
  return <section className="section-shell py-14 sm:py-20"><p className="eyebrow">{bn ? "ডিজিটাল শোরুম" : "Digital showroom"}</p><h1 className="page-title mt-4">{bn ? "পণ্যসমূহ" : "Products"}</h1><p className="mt-5 max-w-2xl leading-8 text-muted-foreground">{bn ? "বিভাগ বেছে বা নাম লিখে আপনার প্রয়োজনের পণ্য খুঁজুন।" : "Choose a category or search by name to find what you need."}</p><div className="mt-10 border-y border-border py-5"><div className="relative max-w-xl"><Search className="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground"/><Input value={search.q} onChange={(event) => navigate({ search: (prev) => ({ ...prev, q: event.target.value }), replace: true })} aria-label={bn ? "পণ্য খুঁজুন" : "Search products"} placeholder={bn ? "পণ্যের নাম লিখুন" : "Search products"} className="h-12 pl-12 pr-12"/>{search.q && <Button variant="ghost" size="icon" className="absolute right-0 top-1/2 -translate-y-1/2" onClick={() => navigate({ search: (prev) => ({ ...prev, q: "" }), replace: true })} aria-label={bn ? "সার্চ মুছুন" : "Clear search"}><X/></Button>}</div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{[{ id: "all", label: t.common.all }, ...categories.map((item) => ({ id: item.id, label: item.label[language] }))].map((item)=><Link key={item.id} to="/products" search={{ category:item.id,q:search.q }} className={`inline-flex min-h-11 shrink-0 items-center border px-4 text-sm font-semibold ${search.category===item.id?"border-primary bg-primary text-primary-foreground":"border-border bg-background text-muted-foreground hover:text-foreground"}`}>{item.label}</Link>)}</div></div>{filtered.length===0 && <div className="py-20 text-center" aria-live="polite"><Shapes className="mx-auto size-10 text-gold"/><h2 className="mt-5 font-display text-3xl font-semibold">{search.q ? (bn?"কোনো পণ্য পাওয়া যায়নি":"No products found") : (bn?"পণ্যের তালিকা প্রস্তুত হচ্ছে":"The product catalogue is being prepared")}</h2><p className="mx-auto mt-3 max-w-lg leading-7 text-muted-foreground">{search.q ? (bn?"অন্য নাম লিখে দেখুন বা সব পণ্য দেখুন।":"Try another search or view all products.") : (bn?"যাচাই করা ক্যাটালগ যোগ হলে পণ্যগুলো এখানে দেখা যাবে।":"Verified products will appear here when the catalogue is added.")}</p>{search.q && <Button className="mt-7" onClick={() => navigate({ search:{category:"all",q:""} })}>{bn?"সব পণ্য দেখুন":"View all products"}</Button>}</div>}</section>;
}